### ISSUE TITLE
Implementation of Ruudk\Payment\StripeBundle\Controller\NotificationController

### ISSUE THREAD

**Issue by vasekjares** [ruudk/PaymentStripeBundle#1]
Missing implementation of Ruudk\Payment\StripeBundle\Controller\NotificationController

**Comment by EricGrivilers** [comment]
Did you configure JMSPaymentCoreBundle ? 
http://jmsyst.com/bundles/JMSPaymentCoreBundle

**Comment by ruudk** [comment]
hmm, I accidentally added this to services.xml because I copied this bundle from https://github.com/ruudk/PaymentMollieBundle
