### ISSUE TITLE
symfony3

### ISSUE THREAD

**Issue by o-luwafemi** [ruudk/PaymentStripeBundle#11]
i cant install it on symfony 3
"Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for ruudk/payment-stripe-bundle ^2.0 -> satisfiable by ruudk/payment-stripe-bundle[2.0.0].
    - Conclusion: remove symfony/symfony v3.3.5
    - Conclusion: don't install symfony/symfony v3.3.5
    - ruudk/payment-stripe-bundle 2.0.0 requires omnipay/stripe ~2.0 -> satisfiable by omnipay/stripe[2.1.1, V2.4.7, v2.0.0, v2.1.0, v2.1.2, v2.2.0, v2.2.1, v2.3.0, v2.3.1, v2.3.2, v2.3.3, v2.4.0, v2.4.1, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6]."

**Comment by Kleinast** [comment]
Same problem here wih symfony 3.4.23

**Comment by ruudk** [comment]
This bundle is no longer maintained.

**Comment by ruudk** [comment]
Feel free to fork this.
