### ISSUE TITLE
"The source parameter is required"

### ISSUE THREAD

**Issue by hidabe** [ruudk/PaymentStripeBundle#5]
When I try to do payment with it from JMSPayment, symfony return me: "The source parameter is required"

**Comment by hidabe** [comment]
Ok, i have found that source parameter should be pass as argument, but name for this argument is: "token", if I add it to form parameteres, "The source parameter is required" is fixed. But i have new error: "Transaction was not successful: No such token: ..."

What about token i should use?

Thanks

**Comment by hidabe** [comment]
I am here again ;)

Ok, i have read stripe documentation, i know now about token parameter:

```
// Get the credit card details submitted by the form
$token = $_POST['stripeToken'];
```

But... then, i need build credit form manually?

**Comment by danielsippel** [comment]
+1

**Comment by lefevrejeremy** [comment]
I have exactly the same issue, I'm following the tutorial written on JMS website, how did you fixed that?

**Comment by tdubuffet** [comment]
Hi,
It's not an error. Before the payment form, you must use stripe.js Form ([https://stripe.com/docs/stripe.js?](url)). This form return a token.  This token must be injected into the JMS form.

Bye

**Comment by ruudk** [comment]
Would be great to add this to the readme. Can somebody create a PR?

**Comment by belhadj-haythem** [comment]
Hello, 
Did someone already solved the issue ? where to put the generated token in the JMSPaymentBundle ?? 
is it in the form or where ?

**Comment by zozoh94** [comment]
You have to change the #jms_choose_payment_method_data_stripe_checkout_token value with the result of the request to the stripe API (method createToken) with Stripe JS. This is an example with some JQuery:
`
function stripeTokenHandler(token) {
  $('#jms_choose_payment_method_data_stripe_checkout_token').val(token.id); 
  // Submit the form
  document.getElementById('payment-form').submit();
}

$(document).ready(function(){
  if($('#payment-form').length > 0) {
    $("#jms_choose_payment_method_method_0").prop('checked', true);
    
    var stripe = Stripe(global.stripePublic);
    var elements = stripe.elements();

    // Create an instance of the card Element
    var card = elements.create('card');

    // Add an instance of the card Element into the `card-element` <div>
    card.mount('#card-element');

    card.addEventListener('change', function(event) {
      var displayError = document.getElementById('card-errors');
      if (event.error) {
	displayError.textContent = event.error.message;
      } else {
	displayError.textContent = '';
      }
    });

    // Create a token or display an error when the form is submitted.
    var form = document.getElementById('payment-form');
    form.addEventListener('submit', function(event) {
      event.preventDefault();

      stripe.createToken(card).then(function(result) {
	if (result.error) {
	  // Inform the user if there was an error
	  var errorElement = document.getElementById('card-errors');
	  errorElement.textContent = result.error.message;
	} else {
	  // Send the token to your server
	  stripeTokenHandler(result.token);
	}
      });
    });
  }  
});
`
