### ISSUE TITLE
Symfony 3.2

### ISSUE THREAD

**Issue by AVATOR** [ruudk/PaymentStripeBundle#7]
Hi.
Please, add support to Symfony 3.2.

**Comment by ruudk** [comment]
Can you make a PR?

**Comment by psrpinto** [comment]
You need to *force* `symfony/event-dispatcher` to v2.8. This is a know issue with omnipay which will be fixed on v3 of omnipay.

```
composer require symfony/event-dispatcher:^2.8
composer require ruudk/payment-stripe-bundle
```

This should probably be added to the installation instructions. See https://github.com/ruudk/PaymentStripeBundle/pull/6#discussion_r85154923

**Comment by AVATOR** [comment]
@regularjack Thanks!
@ruudk add information to the installation instructions, please.

**Comment by ruudk** [comment]
@regularjack @AVATOR Can you do a PR for changing the installation instructions :) ?

**Comment by AVATOR** [comment]
@ruudk I have created pull request https://github.com/ruudk/PaymentStripeBundle/pull/8
